### ISSUE TITLE
DartDoc for Dart SDK shows internal interfaces.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/dartdoc#1173]
See https://github.com/dart-lang/sdk/issues/26643

Basically it's exposing `EfficientLength` from `dart:_internal`.
Is this something that should be fixed in the DartDoc tool, or is there a way to hide the interface in the SDK source?

**Comment by jcollins-g** [comment]
In some cases dartdoc will display interfaces intended to be "internal only".  Dartdoc now warns on that issue as of #1390 but we don't actually do much about it ourselves yet.  The SDK could hide EfficientLength by creating a public abstract class and otherwise modifying the inheritance so that the public classes don't extend private classes.

That shouldn't be strictly necessary, though.  Presumably the end-goal here is to pretend that EfficientLength doesn't exist; that public classes that implement it actually don't implement it and declare all their methods and such themselves, etc.  There will be some places where we can't do this, e.g. if a class is named as the type of a parameter to a real public function, but in most other cases there should be something dartdoc can do about this.

**Comment by jcollins-g** [comment]
Elevating to P2 as there's been some traffic on questions related to this bug.

**Comment by jcollins-g** [comment]
Fixed in #1524.
