### ISSUE TITLE
Ensure: methods with many parameters are formatted well

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#122]
Was: https://github.com/dart-lang/dartdoc-viewer/issues/40

If you have a method with many parameters, the DartDoc output does not look very good. For example, look at pkg/intl/lib/date_symbols.dart, which has a constructor with 24 parameters.

**Comment by sethladd** [comment]
Suggestions very welcome. The specific method page lists each parameter on its own line.

**Comment by sethladd** [comment]
A method/function's signature has its own line. Any wrapping happens naturally. Suggestions welcome, but closing for now.

**Comment by alan-knight** [comment]
The problem is that the natural wrapping gets very difficult to read. Here's the example from the original bug. http://www.dartdocs.org/documentation/intl/0.12.2/index.html#intl/date_symbols.DateSymbols@id_DateSymbols-
Suggestions would be either to put each parameter on its own line once there's more than a certain number of them or run the dart_style algorithm on it and do whatever it does.

**Comment by sethladd** [comment]
For the dedicated page for methods/functions/callable-things, we put each parameter on a new line.

For the summary page (classes, libraries), I love the suggestion of running dart_style on it. At a minimum, we should break on a type annotation, and not just on a space.

Reopening.
