### ISSUE TITLE
'Properties' link in masthead is broken in Enums

### ISSUE THREAD

**Issue by filiph** [dart-lang/dartdoc#1225]
Reproduce (on api.dartlang.org):

1) Open an Enum page like https://api.dartlang.org/stable/1.18.0/dart-io/FileLock-class.html
2) Click on PROPERTIES in the masthead

Expected result: page jumps to Properties of the Enum

Actual result: nothing happens

The link goes to #properties, which is a non-existent anchor on the page. There is an anchor for #instance-properties, though.

**Comment by chalin** [comment]
Yes, we're still seeing this for the AngularDart docs; e.g., https://webdev.dartlang.org/angular/api/angular2.compiler/PropertyBindingType-class

cc @kwalrath

**Comment by chalin** [comment]
Just curious, do we have tests cases covering this -- and other recently closed -- issues?

**Comment by jcollins-g** [comment]
There is presently no integration test that verifies the correctness of masthead links on generated pages specifically, but these are covered by the somewhat less-than-adequate generated files test.  (Seeing as that used to verify that it was wrong, that's why I consider it less than adequate).

Other issues generally have had tests written for them, or required work like #1360.

We can certainly improve the grind link checker further (see newly filed #1376) for this specific issue.
