### ISSUE TITLE
Remove cc license from default footer-text

### ISSUE THREAD

**Issue by damien-git** [dart-lang/dartdoc#1262]
Pages generated by dartdoc have the following footer (which is not changed with the --footer option): the name of the application, the Dart icon, and "cc license". My application is not distributed under the cc license, but this makes it look like it is. Is there any way to change that ?

**Comment by devoncarew** [comment]
No feature for that currently, but you can post-process the generated docs.

I believe that cc license isn't meant to apply to the package, but to the generated docs.

**Comment by damien-git** [comment]
Then maybe dartdoc could write "Dart" or "generated by dartdoc" instead of the package name before the license.

**Comment by sethladd** [comment]
Good idea. Patches welcome!

**Comment by kevmoo** [comment]
@devoncarew @jcollins-g We should change the default here. We shouldn't guess the license.

We could add a field to the pubspec that contains dartdoc-specific info, like the doc license.

**Comment by jcollins-g** [comment]
I think licensing information probably does belong in pubspec.yaml because it isn't dartdoc specific.  I don't want dartdoc-specific options in pubspec.yaml; instead, I'm planning a dartdoc_options.yaml similar to analysis_options.yaml.

**Comment by kevmoo** [comment]
Sure. I guess if a package author wants tweak things there they can.

The "default" should be nothing – again, we shouldn't be guessing for the user.

**Comment by jcollins-g** [comment]
A simple change to dartdoc + a change to the SDK when upgrading the version is required here.

**Comment by kevmoo** [comment]
Glad it's simple 😄

**Comment by kwalrath** [comment]
dartdoc_options.yaml sounds great. What do you think would be there?

**Comment by jcollins-g** [comment]
@kwalrath I want to place there most options that are currently command line flags, such as header/footer, whether to group categories, etc.  Additionally, similar to analyzer, I want a section for controlling dartdoc warnings and which to treat as errors or warnings.  The code is actually almost ready for that breakout but we need somewhere nice to land the configuration options rather than just greatly expanding our command line flags:

https://github.com/dart-lang/dartdoc/blob/fb2c2d0433b2e181bf6ad420cecf508bb1fbc9d9/lib/src/model.dart#L3307
