### ISSUE TITLE
document the `@example` option

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1312]
We should document how to use `@example`, probably in the readme (https://github.com/dart-lang/dartdoc/blob/master/README.md).

@chalin

**Comment by chalin** [comment]
We now have two very similar mechanisms for adding code fragments to API docs: `@source` and `@example`. The former is handled outside of dartdoc.

I'd suggest that we drop support for `@example` in favor of `@source`.

@kwalrath @kevmoo @sethladd
cc @matanlurey

**Comment by sethladd** [comment]
Thanks for the head's up. Where can I learn more about the differences between the two mechanisms?

**Comment by chalin** [comment]
- See https://github.com/dart-lang/dartdoc/pull/1295#issuecomment-267492095 for information about `{@example}` directives.
- See the https://github.com/chalin/api_doc_updater README for information about `{@source}`. Also, this [wiki page](https://github.com/dart-lang/site-webdev/wiki/Working-on-API-docs#adding-examples) documents how we use the `api_doc_updater` for AngularDart.

**Comment by chalin** [comment]
Btw, `{@example}` as it is currently implemented, is essentially just an "include" directive: when processed, the `{@example}` line gets replaced with the content of the named file (modulo file name mangling when a region name is also provided).

If such a feature is useful, I suppose that we can keep it, but then it should be renamed to something like `@include` (and we'd drop the region parameter).

**Comment by sethladd** [comment]
Why not roll @source into dartdoc?

Agreed, there probably should be one way to insert a portion of one file into another.

But, as a user of dartdoc, who might get a package from the wild and I want to build its docs, don't ask me to also download another tool :)

**Comment by matanlurey** [comment]
I agree - would love this just to be part of dartdoc.

**Comment by chalin** [comment]
dartdoc and the `@source` tool are separate because they are used as part of separate workflows, to achieve distinct goals:

- dartdoc is used to **generate HTML pages** _from_ source code.
- The `@source` tool (`api_doc_updater`) is used to **update source code** API comments.

I.e., `api_doc_updater` is more like `dartfmt`.

Think of it this way: would you want to merge the capabilities of `dartfmt` into dartdoc?
Probably not. Developers run `dartfmt` on their source directly. In the same way, developers run the `api_doc_updater` on their sources directly.

So, if you get a package from the wild, you don't have to worry about `@source` directives since the package authors will have had to ensure that `@source` directives were already processed.

If you feel that the `api_doc_updater` _must_ be merged into a standard tool, then it would make more sense to merge its capabilities into `dartfmt` (which I had originally considered, but I wanted to get the prototype out ASAP so that we could gather feedback on its suitability, possible other features, etc).

**Comment by sethladd** [comment]
> since the package authors will have had to ensure that @source directives were already processed.

Is that true? Do pub package authors publish packages with generated HTML docs?  (just curious, I don't think I've seen that, but I could be wrong)

I don't see the equivalence of dartfmt and source-inclusion. The former rearranges my code, but it's functionality identical. The later changes the contents and makes the output much more useful.

What is the workflow today for a developer that has a local copy of AngularDart and wants to make/have a copy of its HTML docs?

**Comment by chalin** [comment]
Ah, I believe that there is a misunderstanding about how `@source` is typically used. 

> [dartfmt] rearranges my code, but it's functionality identical. The later changes the contents and makes the output much more useful.

`dartfmt` is idempotent: it only rearranges code when it is not already in a dartfmt-approved layout.
`api_doc_updater` is also idempotent: it only changes the content of source files when code fragments inlined in the API doc comments are out-of-date.

Consider this excerpt of the [`Directive` class API doc comments](https://github.com/dart-lang/angular2/blob/master/lib/src/core/metadata.dart#L19):
```
/// An annotation that marks a class as an Angular directive, allowing you to
/// attach behavior to elements in the DOM.
///
/// ```dart
/// // {@source "docs/attribute-directives/lib/highlight_directive_1.dart"}
/// library attribute_directives.highlight_directive;
///
/// import 'package:angular2/core.dart';
///
/// @Directive(selector: '[myHighlight]')
/// class HighlightDirective {
///   HighlightDirective(ElementRef element) {
///     element.nativeElement.style.backgroundColor = 'yellow';
///   }
/// }
///
/// ```
///
/// Use `@Directive` to mark a class as an Angular directive and provide
/// additional metadata that determines how the directive should be processed,
/// instantiated, and used at runtime. ...
class Directive extends Injectable { ...
```

Notice the **code inside the markdown code block** (triple back ticks). If you run `api_doc_updater` over this file, nothing will happen because the code fragment is up-to-date. With the code fragment already in the file, this means it can be viewed in an IDE, or used to generate HTML docs, without any extra processing.

Does this make things clearer?

**Comment by sethladd** [comment]
Ah, that's cool. And that definitely clears things up. Thanks!

(I feel like we should move the existential question to a different issue. To go back to the original intent for the issue, there's a feature that we support that is undocumented. :)

**Comment by chalin** [comment]
Ok, I think this is the way you wanted issues separated out:
- #1347 - drop `@example`, or rename it to `@insert` or `@include`
- https://github.com/chalin/api_doc_updater/issues/2 - merge the functionality of `api_doc_updater` into a standard dart tool

If not, let me know. If so, please add comments to each of these other issues.

**Comment by crasm** [comment]
I was looking for a way to add an existing example file to a dartdoc and came across this. I tried a couple of obvious permutations (like `  /// {@example example/simple.dart}`) but none of them worked. Was this already removed from dartdoc, and #1347 never got updated?

**Comment by srawlins** [comment]
Hi, sorry yes, this is being removed. It was recently deprecated in https://github.com/dart-lang/dartdoc/commit/0e1a6d94a6cb5dd487a19ebb68980e34ac6154ba. 

You can watch https://github.com/dart-lang/dartdoc/issues/3503 for updates on what syntax we might offer for explicit samples, examples, and snippets.

**Comment by srawlins** [comment]
Recently removed.
