### ISSUE TITLE
Dartdoc generation hangs forever with phaser package

### ISSUE THREAD

**Issue by astashov** [dart-lang/dartdoc#1314]
Steps to repro:

1. Install Dart 1.21.0
2. `pub cache add phaser --version 2.6.2-beta`
3. `git clone https://github.com/dart-lang/dartdoc.git`
4. In the dartdoc dir, `pub global activate --source path .`
5. Then, run dartdoc, like:

```
pub global run dartdoc --output=./documentation/phaser/2.6.2-beta --hosted-url=https://www.dartdocs.org --rel-canonical-prefix=https://www.dartdocs.org/documentation/phaser/latest --input=/Users/anton/.pub-cache/hosted/pub.dartlang.org/phaser-2.6.2-beta
```

Observe it goes for a bit, and then hangs forever

```
Generating documentation for 'phaser' into /Users/anton/documentation/phaser/2.6.2-beta/

parsing /Users/anton/.pub-cache/hosted/pub.dartlang.org/phaser-2.6.2-beta/lib/microsoft.dart...
parsing /Users/anton/.pub-cache/hosted/pub.dartlang.org/phaser-2.6.2-beta/lib/p2.dart...
parsing /Users/anton/.pub-cache/hosted/pub.dartlang.org/phaser-2.6.2-beta/lib/phaser.dart...
parsing /Users/anton/.pub-cache/hosted/pub.dartlang.org/phaser-2.6.2-beta/lib/pixi.dart...
```

It seems like it's stuck on this line:

https://github.com/dart-lang/dartdoc/blob/57c283e019d1f292e6ee398f2c0c47c6c51b8ecd/lib/dartdoc.dart#L255

I tried the old trick with `analysisOptions.cacheSize = 512`, it didn't help...
Tried to debug it a bit, but didn't get far. Probably need help of @bwilkerson here.

**Comment by devoncarew** [comment]
@astashov - somewhat related - you may want to switch dartdocs.org over to generating docs based on the dartdoc from the sdk. That will be sure to use the latest analyzer.

**Comment by keertip** [comment]
@astashov , did you try running the dartdoc that ships with the sdk instead of getting it using pub? Are you still seeing this issue?

**Comment by jcollins-g** [comment]
Trying with 1.23.0-dev.11.5, phaser-2.6.2-beta has analysis errors and fails now because it has classes that try to extend themselves:

~~~~
[error] 'Graphics' can't extend itself. at lib/phaser.dart, line 2678.
[error] 'Matrix' can't extend itself. at lib/phaser.dart, line 4213.
[error] 'ContactMaterial' can't extend itself. at lib/phaser.dart, line 5709.
[error] 'DistanceConstraint' can't extend itself. at lib/phaser.dart, line 5715.
[error] 'GearConstraint' can't extend itself. at lib/phaser.dart, line 5744.
[error] 'LockConstraint' can't extend itself. at lib/phaser.dart, line 5771.
[error] 'Material' can't extend itself. at lib/phaser.dart, line 5783.
[error] 'PrismaticConstraint' can't extend itself. at lib/phaser.dart, line 5807.
[error] 'RevoluteConstraint' can't extend itself. at lib/phaser.dart, line 5825.
[error] 'Point' can't extend itself. at lib/phaser.dart, line 6206.
[error] 'RenderTexture' can't extend itself. at lib/phaser.dart, line 6641.
[error] 'Rope' can't extend itself. at lib/phaser.dart, line 6767.
[error] 'RoundedRectangle' can't extend itself. at lib/phaser.dart, line 6911.
[error] 'Sprite' can't extend itself. at lib/phaser.dart, line 7214.
Generation failed: encountered 14 analysis errors.
~~~~

Reading the code, it certainly does seem to be doing that (how this code could possibly work is an open question).  Probably the infinite loop behavior was fixed in the analyzer at some point since this bug was filed.
