### ISSUE TITLE
Implement generic function type syntax in dartdoc

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/dartdoc#1321]
This is the dartdoc-implementation issue for https://github.com/dart-lang/sdk/issues/27527.

**Comment by devoncarew** [comment]
punted to 1.23

**Comment by mit-mit** [comment]
@devoncarew who should this be assigned to?

**Comment by jcollins-g** [comment]
I'm willing to take a look, but it looks like from the description, it will be dependent on analyzer support.

**Comment by devoncarew** [comment]
@jcollins-g, thanks! If this needs a new analyzer library, we can either backport the necessary work to the 0.29 release of analyzer, release an entirely new 0.30 version, or solve the issue by moving dartdoc into the sdk repo.

**Comment by devoncarew** [comment]
It looks like dart_style (https://github.com/dart-lang/dart_style/issues/563) will also need a version of the analyzer w/ generic function type support.

**Comment by mit-mit** [comment]
Analyzer is done!

**Comment by jcollins-g** [comment]
I'll start looking at this today.

**Comment by dgrove** [comment]
The last full push to trunk is Wednesday early morning. Is this likely to land by then?

**Comment by jcollins-g** [comment]
Implementation & tests complete, assuming I understand the feature correctly.  Blocking on landing of [cl 2778253002](https://codereview.chromium.org/2778253002/), landing a backport of this and related CLs to the analyzer 0.29 branch in SDK, publishing the new analyzer package, and then submitting my change to dartdoc.  So it is going to be hard to get all that done in the next several hours.

Declared NewGenericTypedef as below:

`/// A typedef with the new style generic function syntax.`
`typedef NewGenericTypedef<T> = List<T> Function<T>(int);`


Screenshots:
![screenshot from 2017-03-28 11 02 28](https://cloud.githubusercontent.com/assets/14116827/24420152/b6371758-13a6-11e7-9596-f38f3767e1cc.png)
![screenshot from 2017-03-28 11 03 24](https://cloud.githubusercontent.com/assets/14116827/24420156/b9dd0bf6-13a6-11e7-8114-1728df38d693.png)

**Comment by keertip** [comment]
Looks good! See the generic type info :+1:

**Comment by jcollins-g** [comment]
@bwilkerson I think these are the blocking items we need from analyzer:
-  [CL 2778253002](https://codereview.chromium.org/2778253002/) must land
-  Above CL and other CLs needed to make [this](https://github.com/dart-lang/dartdoc/blob/generic-function-types/testing/test_package/lib/fake.dart) analyze cleanly must be published in an analyzer package, so we can avoid errors like line 126-132 [here](https://ci.appveyor.com/project/devoncarew/dartdoc/build/1.0.1825)

**Comment by jcollins-g** [comment]
CL 2778253002 has landed.

With this change, old and new versions of dartdoc at least do not crash or have missing docs, though the older dartdoc does have a cosmetic problem with some extra whitespace in the parameter list which I fixed in [the branch](https://github.com/dart-lang/dartdoc/tree/generic-function-types).

We can choose any of:
* Do nothing from here on for 1.23, leaving the extra whitespace in dartdoc for the new syntax as a bug.
* Switch the [DEPS](https://github.com/dart-lang/sdk/blob/master/DEPS#L61) in the SDK to point to [the branch](https://github.com/dart-lang/dartdoc/tree/generic-function-types) for dartdoc
* Wait for published versions of analyzer, then publish dartdoc, then update DEPS and ship the new dartdoc that way, either as a 1.23 cherrypick or with the next version.

**Comment by jcollins-g** [comment]
Actually, it turns out the cosmetic problem was introduced after 0.9.12.  So this should not be a blocking issue at all for 1.23 -- just use 0.9.12 dartdoc as it is currently configured.

We'll still need to get this untangled eventually for flutter and other non-SDK customers, so I'd prefer to leave the issue open until this actually can be committed to dartdoc head.

**Comment by devoncarew** [comment]
Sounds like we still want to track, but can drop the `1.23` label.

**Comment by bwilkerson** [comment]
The example given isn't a very good one because there are two type parameters with the same name. A better example would be
```
typedef NewGenericTypedef<T> = List<S> Function<S>(T);
```
The Dartdoc also appears to miss the fact that there are two lists of type parameters, so I think it needs some updating. Whether that needs to happen before 1.23 is someone else's call.

**Comment by jcollins-g** [comment]
Here are some screenshots of a better example.

![screenshot from 2017-03-28 14 32 59](https://cloud.githubusercontent.com/assets/14116827/24428546/b39cd77c-13c3-11e7-94fa-c4d1f227a508.png)
![screenshot from 2017-03-28 14 31 18](https://cloud.githubusercontent.com/assets/14116827/24428552/b5a27e8c-13c3-11e7-9d81-d9f8dec2b300.png)

As for "two lists of type parameters", what would you expect to see here?

**Comment by jcollins-g** [comment]
Discussed with Brian; since the type parameter is unresolved it makes sense to put that after NewGenericTypedef in the example above.  (So it would be List<S> NewGenericTypedef<S>(T, int, bool) )

Which while a little confusing looking is also more accurate, as it answers the question "where did <S> come from".  I'll put this in next.

**Comment by jcollins-g** [comment]
Now that I understand the feature better I think this really does need to be improved.

New screenshots showing the change:

![screenshot from 2017-03-29 09 35 42](https://cloud.githubusercontent.com/assets/14116827/24465805/5947b2b0-1463-11e7-99b3-05cdb526d214.png)
![screenshot from 2017-03-29 09 36 09](https://cloud.githubusercontent.com/assets/14116827/24465810/5c2af2d0-1463-11e7-828a-ed6a565b9637.png)

It's still not great; note how <S> appears in some places and <T> in others, which is confusing.  But it seems more correct than before.

**Comment by jcollins-g** [comment]
[CL 2787513003](https://codereview.chromium.org/2787513003/) uploaded for analyzer, [generic-function-types branch](https://github.com/dart-lang/dartdoc/tree/generic-function-types) updated with new tests.  dartdoc branch is still pending a released version of analyzer containing these changes.

**Comment by mit-mit** [comment]
@jcollins-g @bwilkerson where are we at with this one?

**Comment by jcollins-g** [comment]
I'm going to tag the branch and manually test dartdoc merged with the SDK today, and we can ship an SDK that contains dartdoc (even though dartdoc head is broken).

**Comment by jcollins-g** [comment]
proposed tag for 0.9.14-dev:  [b1f60db4e0d1550487d622dd62d8225c96682dc7](https://github.com/dart-lang/dartdoc/commit/b1f60db4e0d1550487d622dd62d8225c96682dc7)

**Comment by devoncarew** [comment]
@jcollins-g, with https://codereview.chromium.org/2795653003/, we're good to close this?

**Comment by jcollins-g** [comment]
Now that the revision is merged to the SDK, I'm OK with removing the 1.23 tag.  Don't want to close until we have an analyzer published package containing the changes.

**Comment by jcollins-g** [comment]
Support is in published dartdoc with 0.12.0.
