### ISSUE TITLE
Support default document (index.html) for cleaner URLs

### ISSUE THREAD

**Issue by eseidelGoogle** [dart-lang/dartdoc#1346]
Right now to actually get to a library root page you need to know dartdocs pattern of doing name-library.html:
https://docs.flutter.io/flutter/dart-async/dart-async-library.html

https://docs.flutter.io/flutter/dart-async/
would just get you a 404.

Obviously we could fix this in Flutter's doc generation script as well, but seems like something maybe all dartdoc users might want?

**Comment by sethladd** [comment]
Presumably this means there is an index.html under dart-async/. Could there be a thing called "index" inside of a Dart library? If so, what kind of structure would we need to put all the things into sub-directories so that they don't collide with a name called "index" ?

We might be able to teach Firebase what the "index.html" file is actually called. But, that would be a solution specific to Flutter's docs. I think assuming an "index.html" is a safe assumption, so many web servers will look for that file.

Just need to be careful here with collisions... but yeah, +1 for anything we can do for more beautiful URLs

**Comment by kevmoo** [comment]
https://api.dartlang.org/stable/1.24.3/dart-core/

Is soooo much nicer than

https://api.dartlang.org/stable/1.24.3/dart-core/dart-core-library.html

**Comment by kevmoo** [comment]
CC @athomas

**Comment by srawlins** [comment]
CC @kevmoo @gspencergoog would you say this is still very desirable? I have [a PR out](https://github.com/dart-lang/dartdoc/pull/3895).

Re [collisions](https://github.com/dart-lang/dartdoc/issues/1346#issuecomment-280709414), @sethladd, good catch! Most pages are suffixed with a 'kind', like [Ticker-class.html](https://api.flutter.dev/flutter/scheduler/Ticker-class.html), but enums ([AppLifecycleState](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState.html)), properties ([channelBuffers](https://api.flutter.dev/flutter/dart-ui/channelBuffers.html)), functions ([clampDouble](https://api.flutter.dev/flutter/dart-ui/clampDouble.html)), typedefs ([ChannelCallback](https://api.flutter.dev/flutter/dart-ui/ChannelCallback.html)) are not suffixed, so any named `index` would collide with this. With that lower-case, this would particularly be a top-level property or top-level function that could cause a collision. I should probably use new paths for those like `clampDouble-function.html`, and write redirecting files.

**Comment by kevmoo** [comment]
I think this is still VERY desirable.

**Comment by gspencergoog** [comment]
Yes, I agree.
