### ISSUE TITLE
[new ui.Gradient.linear] doesn't linkify

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#1402]
There's a couple of places where we refer to otherwise-ambiguous terms via the import prefix, e.g. `[ui.Image.width]`, `[new ui.Gradient.linear]`.

**Comment by jcollins-g** [comment]
This is going to be a challenging one to fix correctly.  Because of canonicalization, we can no longer use commentRefs as a way to leverage the analyzer directly.   So dartdoc's old fallback of attempting to compute fully qualified names for ModelElements and looking up things like ui.Image.width in a big table is now the primary means of doing non-local lookups.  That doesn't work when import prefixes are involved.  Out of necessity, #1390 made the old fallback more robust and and it now works for all the cases where it could, but it didn't alter the basic design.

For this fix, ModelElements will need to implement a "lookup" function, break down a name into its component parts, and traverse the ModelElement tree directly, so that special cases like import prefixes can be detected and handled.  This will be more robust and likely better performing than the old method ever could be but is a non-trivial design change.
