### ISSUE TITLE
dartdoc build is failing

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#1478]
This is for the flutter bot:

https://travis-ci.org/dart-lang/dartdoc/jobs/260396830

This happened on the weekly cron job rebuild of dartdoc, so perhaps this was due to a change in the flutter source code?

/cc @jcollins-g

**Comment by jcollins-g** [comment]
Going to need to get this fixed before publishing a new dartdoc.  Elevating to P0 as a result.

**Comment by jcollins-g** [comment]
There seems to be a real bug going on where we don't recognize an accessor is Inheritable when it is represented by a MultiplyInheritedPropertyAccessorElementImpl.  Fixing that is fairly straightforward, verifying the fix breaks nothing else is a bit harder.

**Comment by kevmoo** [comment]
@jcollins-g – any idea why we're hitting w/ only w/ Flutter?

**Comment by jcollins-g** [comment]
Not yet.  But in all my spelunking in dartdoc prior to a month and a half ago, I had never heard of a MultiplyInheritedPropertyAccessorElementImpl object from the analyzer.  The object type is not new in the analyzer, but something new, somewhere has caused it to start appearing when building flutter docs using the head version of dartdoc.

**Comment by jcollins-g** [comment]
This seems to be related to recent changes in head, including #1466, combined with changes in flutter package later on.   The new synthetic construction of Fields to solve #1394 is missing a case where an accessor's variable method can be null, because of multiple inheritance paths for an accessor.  This is not quite trivial to solve, so I will be deferring this issue and releasing 0.13.0+2 as a one line patch to solve #1491.

**Comment by jcollins-g** [comment]
I'd prefer the travis bot to remain broken as a positive signal that we shouldn't release from head until this is fixed.
