### ISSUE TITLE
dartium extraction from SDK causes SDK bot breakage

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1491]
https://uberchromegw.corp.google.com/i/client.dart/builders/dart-sdk-linux-be/builds/15140/steps/generate%20sdks/logs/stdio

Reported by @terrylucas.  Problem is here: https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart#L2335.

a.element is allowed to be null but this code doesn't expect that.

**Comment by terrylucas** [comment]
Janice can you add the 1 line change datadoc gen to v0.13.0+2 (rev of last release v0.13.0+1 and this fix).  Then I can change the DEPS to grab that release.  The problem is the dart-sdk bot failure include zipping the sdk and building the dartdoc any failure with these 2 steps will cause the dart2js bots to not run.

@whesse will look at changing the recipe to separate the sdk zip and upload the sdk  from the dartdoc gen.  However, it would still be nice to get this fix in ASAP to keep the bots green.

**Comment by jcollins-g** [comment]
The one line fix is not enough to make dartdoc pass in flutter using checked mode.  Fortunately for us though, they aren't using checked mode.  That still needs to be dealt with but is a matter for another time.
