### ISSUE TITLE
dartdoc and comment_references lint disagree on [true] and [false]

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/dartdoc#1519]
If one enables the [comment_references](http://dart-lang.github.io/linter/lints/comment_references.html) lint, doing`[true]` or `[false]` is fine.

dartdoc reports these as `unresolved-doc-reference`

...should be consistent

**Comment by kevmoo** [comment]
FYI @pq

**Comment by jcollins-g** [comment]
dartdoc does not currently support keywords in comment references, but this could be added.

**Comment by devoncarew** [comment]
We may want to choose to change the lint here. I'd expect the contents of square brackets to generally be something that resolves to a symbol. For this case, the user should probably write:

    `true`

**Comment by jcollins-g** [comment]
I can also see the argument for `[]` working for true or false, since functionally those work the same as final global bools and when I'm coding, I don't usually make the distinction in my head that these are keywords.

In general, better synchronization between the linter and dartdoc seems like a good idea if we can find the space for it.

**Comment by kevmoo** [comment]
It's not like `true` exists as a top-level field in dart:core, though.
There is nothing for dartdoc to link to.

I'd rather we change linter, IMHO

**Comment by pq** [comment]
This issue was moved to dart-lang/linter#808

**Comment by pq** [comment]
Fix on the linter in flight: https://github.com/dart-lang/linter/pull/809
