### ISSUE TITLE
Dartdoc needs to be migrated to the new analysis driver

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/dartdoc#1586]
The Dart 2.0 features mentioned in https://github.com/dart-lang/sdk/issues/31640 are going to be implemented using the new analysis driver; they aren't guaranteed to be backported to the old analyzer task model.  So in order to ensure that Dartdoc is Dart 2.0 compliant we will need to change Dartdoc to make use of the new analysis driver.

We will probably need assistance from @bwilkerson and @scheglov to determine the proper analyzer entry points for Dartdoc to use.

**Comment by devoncarew** [comment]
also cc'ing @pq, as he has done the migration for the linter, so could provide pointers / links to PRs.

**Comment by jcollins-g** [comment]
Situation is better for dartdoc -- there's only one point at which we grab AnalysisContexts from the analyzer, which is here:

https://github.com/dart-lang/dartdoc/blob/7d3e01f674ca947012e18141643cd2c5cd2a1fe5/lib/src/model.dart#L4853

We can move dartdoc by porting over this small section to whatever can give us analyzer data.

**Comment by pq** [comment]
Cool!

FWIW, here's the relevant PR for the linter migration: https://github.com/dart-lang/linter/pull/754.

Happy to walk you through it whenever.

**Comment by jcollins-g** [comment]
This will also enable interpretation of analysis options files.

**Comment by jcollins-g** [comment]
I started on this yesterday and got dartdoc mostly functioning in the way that it does now (a PR to come soon).

However, it turns out that we can't quite get analysis options file interpretation going as quickly.  The architecture of the analyzer requires there to be one `AnalysisDriver` (or in the old model, `AnalysisContext`) for every analysis options file.  Neither dartdoc nor the command line linter (@pq) operate in this manner currently -- they simply use a single context/driver for all files to be analyzed.  I had misinterpreted "converting to AnalysisDriver" as being equivalent to converting to something that can manage all that for you.

Talked with @bwilkerson and creating something that creates `AnalysisDriver`s for you, manages them, and dispatches addFile() to the right driver is likely beyond the context of dartdoc and should be shared code in the analyzer.

This means that for #1595 we'll need to hack around the errors yet again until we can get the proper API from the analyzer (or, alternatively, give up and implement it ourselves within dartdoc).  In the meantime, this issue will be redefined as simply get us out of using the AnalysisContext objects.
