### ISSUE TITLE
Allow full text search from the search box in Dartdoc

### ISSUE THREAD

**Issue by jcollins-g** [dart-lang/dartdoc#1703]
Set up full-text search capabilities for searching dartdoc.  This could be done either by adding this directly to the search box, or by adding support for an external search (e.g. on the pub site) using generated dartdoc data.

**Comment by klr981** [comment]
### Objective
Discuss the possibility and impact of implementing full text search into the documentation pages for Flutter and Dart generated by dartdoc.

### Discussion
Full Text Search was identified as a high priority for the improvement of the search experience in the Flutter and Dart API documentation sites. Based on the research done for search improvement there were technologies such as Morsel that can provide a full text search experience. Morsel works by providing an index.json file that includes all the information that would be necessary for full text search. An index.json was created using Morsel to compare the size with the existing index.json. It was found that for Flutter the index.json file would increment significantly . 

Another implication of full text search is how the results will be displayed to the user. Designing this feature will require further discussion on which parts of the result content are relevant to the user. 

Finally the current search point system will need to change to include all the content and decide how to provide points to each result with having all the information in the index.json. The current search point system gives the highest point to matches in the json that are exactly as the user input, less points are given in other cases such as library, input that are found but were needed to be lower case.

A possible solution would be to use the search scripts found in[ flutter.dev](https://flutter.dev/) (Figure 1) and [dart.dev](https://dart.dev/) (Figure 2) as a secondary source only to be used if there are no matches in the existing search functionality (Figure 3).

However, this solution is not compatible with the new dark mode feature. This is because it is not possible to override the styling of the results provided by the script (Figure 4). If it were possible to override the CSS styling then this would be an acceptable solution. This solution went through user testing and was accepted by users who participated. 
 Another possible solution is to include a link in the results page when there are no results that would lead the user to the dart.dev search results in a separate site (Figure 5)

#### Figure 1: Flutter.dev search.
![Screenshot 2022-08-26 4 40 36 PM](https://user-images.githubusercontent.com/106621169/187003347-c77d9830-2df0-4531-90c0-587986478a34.png)

#### Figure 2: Dart.dev search.
![Screenshot 2022-08-26 4 41 02 PM](https://user-images.githubusercontent.com/106621169/187003356-9aa620e0-8e52-4ced-89a5-cf354ea5537f.png)

#### Figure 3: The script implementation in the search results page.
![Screenshot 2022-08-24 10 05 02 AM](https://user-images.githubusercontent.com/106621169/187003370-c5e7bf1a-9417-4e83-aa60-0f88c159ebae.png)

#### Figure 4:  Issues with the script CSS colors.
![Screenshot 2022-08-24 10 07 07 AM](https://user-images.githubusercontent.com/106621169/187003385-466a32ca-9c39-4a93-8513-d89e80d29242.png)

#### Figure 5: Current solution that is currently merged in the dartdoc repo.
[new approach.webm](https://user-images.githubusercontent.com/106621169/187003419-65f73e63-8d1f-4eec-938e-f7233079d6f4.webm)
