### ISSUE TITLE
Generation failed: Unknown type GenericFunctionTypeElementImpl

### ISSUE THREAD

**Issue by littlen101** [dart-lang/dartdoc#1709]
Hello, I've been experiencing this error for not only my projects but the demo app as well and wanted to know of any fixes.

[dartdocLog.txt](https://github.com/dart-lang/dartdoc/files/2081845/dartdocLog.txt)

I am trying to get into using it so the only steps to recreate are : 
     1. Use command 'dartdoc' at the root of a flutter project

**Comment by jcollins-g** [comment]
Hi @littlen101, this error is associated with very old versions of dartdoc which don't have the fix for #1495.  Please run:

`dartdoc --version`

If dartdoc version is < 0.13.0+3 you will definitely have this problem, but there are a lot of other flutter related fixes that have been put in so I recommend using the newest version compatible with your version of flutter.  Newer versions of dartdoc come with newer versions of the SDK, but you can also install them with `pub global activate dartdoc`.

**Comment by littlen101** [comment]
Thank you for that. The command ran and said that it downloaded and activated dartdoc 0.15.1 but every time I run the version check it still says 0.9.14. Any recommendations 

I tried running from admin console but that failed as well to update

**Comment by jcollins-g** [comment]
Hi @littlen101 ,

Try following the instructions here: https://www.dartlang.org/tools/pub/cmd/pub-global#running-a-script  to update your path.  Also note a version of dartdoc is shipped with the SDK and if that is in your path before the bin directory for pub, that will take precedence.

I also suggest that you use the version of the Dart SDK included with Flutter (bin/cache/dart-sdk under your `FLUTTER_ROOT`) as that will produce better results for documenting Flutter packages -- you'll be able to use a more modern dartdoc with the newer Dart SDK.

**Comment by littlen101** [comment]
Got it to work thanks again. 

Also dartdoc still requires there be a version number in your pubspec.yaml file for future readers that fix this error and get another.
