### ISSUE TITLE
extra whitespaces in 0.21.1

### ISSUE THREAD

**Issue by isoos** [dart-lang/dartdoc#1762]
0.21.1 introduced an extra whitespace after `<span class="name">[...]</span>` element blocks, e.g.
https://github.com/dart-lang/pub-dartlang-dart/pull/1650/files#diff-88fd39e0fb39d833ac45993a6424225c

**Comment by jcollins-g** [comment]
Is the extra whitespace a more serious problem than P3?

**Comment by isoos** [comment]
P3 sounds perfect.

**Comment by jcollins-g** [comment]
The whitespace changes are because of the categories support; there are now optional fields that will occasionally show up after identifier names inside documentation.  The spaces are from the template, where there's a space between references in the template.

That can probably be eliminated, but I think it would be wise to not depend heavily on whitespace consistency between versions.

**Comment by isoos** [comment]
Sounds fair to me. We don't depend on the whitespaces in any way, just wanted to make sure that there was no unexpected regression.
