### ISSUE TITLE
Newline not detected after bulleted list

### ISSUE THREAD

**Issue by tvolkert** [dart-lang/dartdoc#1969]
Consider the following Dartdoc snippet:

```dart
  /// Lorem Ipsum is simply dummy text of the printing and typesetting industry.
  ///  * Lorem Ipsum has been the industry's standard dummy text ever
  ///    since the 1500s.
  ///  * It was popularised in the 1960s with the release of Letraset sheets
  ///    containing Lorem Ipsum passages.
  /// Where does it come from?
```

This renders the following documentation output:

---
Lorem Ipsum is simply dummy text of the printing and typesetting industry.

 * Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
 * It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages. Where does it come from?
---

Note how the "Where does it come from?" part ends up in the bulleted list, even though it's clearly meant to be its own paragraph.

**Comment by srawlins** [comment]
Sorry, this is how Markdown interprets text on a line following a bullet. Without a paragraph break, its just considered part of the item list. This is how GitHub, CommonMark, and most implementations treat this text. (https://babelmark.github.io/?text=Lorem+Ipsum+is+simply+dummy+text+of+the+printing+and+typesetting+industry.%0A++*+Lorem+Ipsum+has+been+the+industry%27s+standard+dummy+text+ever%0A++++since+the+1500s.%0A++*+It+was+popularised+in+the+1960s+with+the+release+of+Letraset+sheets%0A++++containing+Lorem+Ipsum+passages.%0A+Where+does+it+come+from%3F).
