### ISSUE TITLE
How can I not generate these...

### ISSUE THREAD

**Issue by huakucha** [dart-lang/dartdoc#2220]
![20200525162655](https://user-images.githubusercontent.com/5646613/82794162-9b90ba80-9ea4-11ea-8720-9b7556a23d63.jpg)
When I use dartdoc to generate documents, some system documents will be generated by default, but I do n’t need these, and when pub publish, you are prompted that the file is too large

**Comment by jcollins-g** [comment]
A couple of things @huakucha.  You do not need to generate docs prior to uploading to pub, as pub will take care of building docs for you.  So you can remove the docs from your tree before publishing.

Second, the issue of SDK docs being included in flutter package docs is #1949 and was fixed in dartdoc 0.30.4.  If you're still seeing this problem using a more modern dartdoc, please reopen this issue and I'll take a look!
