### ISSUE TITLE
Users report that font weight is too light

### ISSUE THREAD

**Issue by dnfield** [dart-lang/dartdoc#2374]
More context at https://github.com/flutter/flutter/pull/48073

The basic problem seems to be around how font weights are used. This is probably something that should be fixed in dartdoc, but I do not know what the values actually need to be to make it more friendly to our users.

**Comment by jcollins-g** [comment]
Normally when I make changes here I try to connect it to what we're doing elsewhere in documentation (say, on the Flutter or Dart main websites, or the pub site).  We could try to start there to see if they're doing something better, and try to match it.

**Comment by kwalrath** [comment]
We just made some changes on dart.dev: https://github.com/dart-lang/site-www/pull/2658

**Comment by jcollins-g** [comment]
This actually only appears to be a problem on the flutter site.  Something about the way dartdoc is being used for Flutter is causing very lightweight fonts (perhaps in the custom headers Flutter is adding).  I have noticed that the fonts were different but assumed that was intentional.  Closing and will make a more detailed comment on flutter/flutter#50344.
