### ISSUE TITLE
References to symbols that are inherited are not found.

### ISSUE THREAD

**Issue by gspencergoog** [dart-lang/dartdoc#2389]
If I have a class structure like this:

```dart
class Base {
  /// Performs an action
  void action();
}

class Child extends Base {
}

/// Perform [Child.action] as often as possible.
class Other {
}
```

Then Dartdoc throws an error, saying that `[Child.action]` is an invalid link.  If an explicit override is added to `Child`, then it finds the documentation.

In the wild, this happened when dartdoc was run on https://github.com/flutter/engine/pull/20496, and I had to do [this](https://github.com/flutter/engine/pull/21780/files#diff-5bdf4ae9d67eca0c60df86a01edaddafad727e15c21c59846659c1081bb3141bR801) to make it work.

This makes it hard to refactor code, and in general shouldn't be necessary.

**Comment by jcollins-g** [comment]
The only reason this isn't P0 is that Flutter team has checks against dartdoc and looked before they leapt on creating bad links, and so the bad links don't exist yet.    However, this is really unfortunate for refactoring.  Something odd must be happening here as I am pretty sure we check the trivial case for inheritance.

**Comment by jcollins-g** [comment]
I have verified that the simple cases (as in the example) seem to work.  Will dig deeper into flutter's structure and @gspencergoog 's example to try to tease out what's going on here.

**Comment by jcollins-g** [comment]
By inspection I have discovered at least one problem.  The markdown lookup table filters out non-canonical ModelElements from the global index.  This can result in inherited members failing when referenced via this lookup table, because while a canonical ModelElement does exist for them, they themselves aren't canonical.  The lookup table is only one means by which we resolve names which is probably why prior testing did not find this.

I will fix this and other problems and come up with a more extensive test case.  The comment reference logic hasn't had love lately and is still using some archaic and inefficient means to canonicalize lookup results.

**Comment by jcollins-g** [comment]
It doesn't look like this is completely fixed for users of flutter.  Saw more instances of this when investigating #2426.

**Comment by jcollins-g** [comment]
This, and many other situations like it, should now be corrected with the new lookup code enabled by default on dartdoc 1.0.0.
