### ISSUE TITLE
Provide output path in dartdoc_options.yaml

### ISSUE THREAD

**Issue by Luckey-Elijah** [dart-lang/dartdoc#2476]
With the `dartdoc` tool you can provide an output path like this:

```shell
dartdoc --output "docs"
```

But I would like to be able to add that path to `dartdoc_options.yaml` like this:

```yaml
dartdoc:
  output: "docs"
```

---

I did not find anything in the documentation of `dartdoc` or in the issues to achieve this. If it's there, please let me know and/or add it to the [advanced features](https://pub.dev/packages/dartdoc#dartdoc_optionsyaml) section.

**Comment by jcollins-g** [comment]
Design wise that is not a feature I would choose to implement here.  This is because documentation generation happens in many different contexts for Dart packages, and the runner of, for example, the pub site would not want individual packages themselves determining output directories.

If you want to codify where docs go in your use case, I would suggest using a script instead.  For a dart-only solution, the [grinder package](https://pub.dev/packages/grinder) provides some tools for workflow automation.
