### ISSUE TITLE
``` triggers some sort of syntax highlighting

### ISSUE THREAD

**Issue by Hixie** [dart-lang/dartdoc#2520]
I expected \`\`\` blocks to have no syntax highlighting, but:
https://master-api.flutter.dev/flutter/dart-ui/ChannelBuffers-class.html

**Comment by jcollins-g** [comment]
Before fixing we will need to check how many blocks there are in important packages that may be depending on this and migrate them if need be.

**Comment by srawlins** [comment]
I think _most_ cases of ``` in dart docs are not specified with a language, in which case highlight.js picks one with its "automatic language detection." I would assume most of those cases are Dart code examples, and I'm not sure what highlight.js "detects" in those cases, haha.

This is probably similar to GitHub's treatment of language-non-specific backticks: https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks

**Comment by jcollins-g** [comment]
An alternate way of solving this would be to allow preformatted blocks to specify plain text.

**Comment by parlough** [comment]
Yeah currently we check if nothing is specified [then add Dart](https://github.com/dart-lang/dartdoc/blob/ab44754728ad322f331bef85a77f0ee0c1d253ee/lib/src/render/documentation_renderer.dart#L36-L38).

We could add handling for a custom `plaintext` option then set the class to `plaintext` or `nohighlight` instead.

**Comment by Hixie** [comment]
I would be fine with dartdocs just failing if it comes across a \`\`\` block with no specified language. Defaults are dangerous, and here being explicit is always better for people reading the documentation.

**Comment by jcollins-g** [comment]
Ah, I missed that we add that class in the renderer.    I'm OK with a failure as long it turns out this is rarely encountered enough to be easy to handle in migration, otherwise we'll have to have some sort of migration plan.

**Comment by srawlins** [comment]
dartdoc now warns about language-free code fenced blocks, as of https://github.com/dart-lang/dartdoc/pull/2559.

**Comment by lrhn** [comment]
Is this a *change* of behavior, or codifying existing behavior? 

I was under the impression that DartDoc always used Dart syntax, whether you wrote `dart` or not. Was that true at some point?
Maybe just for indented code, rather than code-braced code?

(Is there an official documentation of the DartDoc format and what it means? Especially code links are not just defined by markdown).

**Comment by jcollins-g** [comment]
> Is this a _change_ of behavior, or codifying existing behavior?
> 
> I was under the impression that DartDoc always used Dart syntax, whether you wrote `dart` or not. Was that true at some point?
> Maybe just for indented code, rather than code-braced code?

A little of both.  Dartdoc uses dart syntax by default in code blocks, but this has caused problems in cases where the user actually intends for there to be plaintext (hence the bug).   The warning changes are intended to encourage being explicit, and plaintext support will be added so that when users want it it is available.

> 
> (Is there an official documentation of the DartDoc format and what it means? Especially code links are not just defined by markdown).

Unfortunately, the specification has not caught up with the implementation.  I wrote the beginnings of a syntax for code links as part of a redesign to fully support extension methods, here:  https://docs.google.com/document/d/11Vzx7PjSNo55YpVEx1BBUlEUPkl6CUpHZ4gFcefBE1I/edit?resourcekey=0-xUb52CNfZwq5FLt8LWSC7A.

Outside of the brief notes here, there is no formal specification for this or other elements of dartdoc behavior.  Arguably, there should be.   Documentation exists in more general form in the README.  @parlough , we should probably update the README/other docs to include more details on code blocks including your changes.
