### ISSUE TITLE
[Records] dartdoc implemention

### ISSUE THREAD

**Issue by itsjustkevin** [dart-lang/dartdoc#3122]

**Comment by srawlins** [comment]
Largely complete in #3233; leaving open for remaining tasks.

**Comment by vsmenon** [comment]
@srawlins - do we have anything to do here?

**Comment by srawlins** [comment]
Hmm, yikes, I have no idea what I meant by "leaving open for remaining tasks." This may not be complete.

**Comment by jcollins-g** [comment]
@srawlins One task that I can see is that there's no bit in test_package_experiments that allows us to check the integration of the feature.   Adding that may also help me discover what was meant by "remaining tasks", if any others exist.

**Comment by srawlins** [comment]
You could add that. I have been writing all new tests as unit tests instead of using the `testing/` folder.

**Comment by jcollins-g** [comment]
@srawlins. Saw that. That's probably for the best for most cases.  Having something browsable helps make sure we didn't miss anything as I don't trust my brain to render all the test HTML as well as an actual web browser.

**Comment by jcollins-g** [comment]
Two things so far I've found that need to be fixed:

- The record type rendering is not very legible, and while it looks Dart-like would not be able to reproduce the type.

![image](https://user-images.githubusercontent.com/14116827/219134127-dbb4b3bd-d0f6-4b09-8cc3-98150619f5ad.png)

The type for this variable should be written out as `(int, double, c: String, d: int)` to match how a type for this variable would be declared.

- We are not preserving the typedef name in the case of records.  While that matches the underlying implementation it is probably not in line with user expectations/friendliness.

Given source:
```
RecordTypedef<double> fromParameterizedRecordType = (3.5, 10, "A string");
```

I would expect:

```
RecordTypedef<double>
```
rather than
```
(double, int, String)
```
or, worse:
```
Record(double $0, int $1, String $2)
```

to be the type of `fromParameterizedRecordType`, with linking.

**Comment by srawlins** [comment]
As long as we stay in-line with the handling of other typedefs, SG.

**Comment by jcollins-g** [comment]
> As long as we stay in-line with the handling of other typedefs, SG.

The second item (preserving typedef names) seems the most clearly in line with other typedef handling, so doing that first.   I'll do some checking to make sure my plan for the first item remains consistent.

**Comment by jcollins-g** [comment]
This should be complete with #3344; any problems discovered later can be separate issues.
