### ISSUE TITLE
we should show the types of consts, if provided in the source code

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/dartdoc#608]
![screen shot 2015-06-19 at 11 04 24 pm](https://cloud.githubusercontent.com/assets/1269969/8311813/b8e4fe1c-198d-11e5-83b7-d32d9ba90696.png)

**Comment by keertip** [comment]
Think the thought was that since we are showing the value of the constants, the type would be redundant.

**Comment by seaneagan** [comment]
I think the type is redundant to have to maintain in *source code*, but since API docs are generated content, it adds no maintenance cost, while making the type more quickly identifiable.

Also, does it only show const values when they're defined as literals?  When they're defined as expressions, I'd assume you'd want to show the actual expression.  For example:

```dart
const foo = 2;
const bar = 3;
const foobar = foo + bar;
```

If showing the value of `foobar` in API docs, I'd want to see `foo + bar` (preferably with clickable sub-expressions) rather than `5`.  In which case I'd have to know the types of `foo` and ` bar` in order to know the type of `foobar`, which I may not.  Also if showing the values of constants of non-intrinsic types e.g. Duration (presumably using `toString()`) it'd be difficult to discern the type from that.  And I wouldn't want to see the type in some cases, and not in others, so I'd say it makes sense to just always show the type.  I presume the analyzer can be used to infer the type when it is omitted in the source code.

Also, since constants *are* properties, *might* make sense to merge "Constants" and "Properties" sections, either by marking each constant individually with "const", or making "Constants" a sub-section of "Properties".

**Comment by sethladd** [comment]
Is showing the value not enough, which implies type?

Perhaps the developer might want to be very specific and mark the variable as a super type, and initialize it with a subtype.

eg

`Parent THING = const Child()`

That would seem to argue that we do want to show the type.

**Comment by seaneagan** [comment]
I think if the dev provides the type in the source code, then it should definitely be shown in the docs.  

The style guide does say to [PREFER providing type annotations on public APIs](https://www.dartlang.org/articles/style-guide/#prefer-providing-type-annotations-on-public-apis).  So IMO question is whether to show the analyzer-inferred type when the type annotation is omitted.  I think it would be pretty useful to show it, possibly with some indication that it was inferred, e.g. via a "grayed out" text color?

**Comment by devoncarew** [comment]
I think if the package author provided an explicit type, we should show that. They may have been using the type annotation for clarity, like `double my_constant = 1`. Where an explicit type annotation is provided, and dartdoc _doesn't_ show the type, it feels like dartdoc is hiding info from me...

**Comment by keertip** [comment]
That  works for me - show type if user has provided type annotation.

**Comment by sethladd** [comment]
sgtm!

**Comment by sethladd** [comment]
I'll give this a shot

**Comment by keertip** [comment]
Thanks!

**Comment by sethladd** [comment]
Options:

![screen shot 2015-07-10 at 1 55 27 pm](https://cloud.githubusercontent.com/assets/5479/8628957/da4485ba-270b-11e5-9f55-e391eb9daf98.png)

or

![screen shot 2015-07-10 at 1 58 55 pm](https://cloud.githubusercontent.com/assets/5479/8628959/ddd8293e-270b-11e5-8b3e-7528d7a6ec1c.png)

**Comment by sethladd** [comment]
Or

![screen shot 2015-07-10 at 2 11 20 pm](https://cloud.githubusercontent.com/assets/5479/8629135/8f0f0d98-270d-11e5-9baf-f65d3da65ef9.png)

**Comment by sethladd** [comment]
Went with this one:

![screen shot 2015-07-10 at 2 27 26 pm](https://cloud.githubusercontent.com/assets/5479/8629398/d1f81120-270f-11e5-8619-0fce2b43f133.png)

**Comment by sethladd** [comment]
CL https://chromiumcodereview.appspot.com/1231213002/

**Comment by sethladd** [comment]
Fixed in 7e8afcdeed82e6f4877906b6a82e2bd24e7c05db
