### ISSUE TITLE
Should be able to search for 'List.length' and get reasonable answers

### ISSUE THREAD

**Issue by sethladd** [dart-lang/dartdoc#837]

**Comment by sethladd** [comment]
cc @keertip @devoncarew this one has come up a few times. If you want to work on a new feature, I can suggest this one :)

**Comment by rakudrama** [comment]
If I type in __List.length__ would be cool to show the documentation before I finished typing.
Say I type **List.len_**, the dropdown shows various matches and the page underneath switches out to the page for List.length. If I press Esc or Backspace, the previous page switches back in.

You could also switch out the page as I navigate the search box dropdown with arrow keys.

In a sense, the page becomes subservient to the search box rather than the search box being a component of the page.

**Comment by sethladd** [comment]
> In a sense, the page becomes subservient to the search box rather than the search box being a component of the page.

Unfortunately, we're not setup for that at all. We're still generally preferring to be simple static HTML files.

**Comment by sethladd** [comment]
Taking a look at this.

I have something working:

![screen shot 2015-10-10 at 2 40 34 pm](https://cloud.githubusercontent.com/assets/5479/10413429/ff235bc4-6f5c-11e5-9103-fbfa53d83c20.png)
