### ISSUE TITLE
Parity with GitHub markdown

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/dartdoc#874]
I understand that these generated docs are a different medium than simple markdown files, but I'd like to express my interest in increasing parity with GitHub's markdown formatting. The main motivation behind this currently is that the `README.md` file is used by default as the landing page for the docs. I often use tables in my project readmes, but these are not currently supported by dartdoc. If working towards parity with GitHub markdown formatting isn't going to be pursued, then I would like to advocate for an alternative approach that has already been suggested: https://github.com/dart-lang/dartdoc/issues/602

**Comment by sethladd** [comment]
Hi,

Thanks for the feedback. We use https://github.com/dart-lang/markdown for our markdown. We'd love to have more fancy markdown support, but it will need to be added to https://github.com/dart-lang/markdown

Please open an issue at https://github.com/dart-lang/markdown for what you need. I'm going to close this one, only because dartdoc itself doesn't plan to address it.
