### ISSUE TITLE
Simplify the DartDoc api usage

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/dartdoc#875]
The CLI is great, but using the API directly to generate docs with dartdoc is non-trivial.

Currently, you have to call `initGenerators` to get a list of default generators, then pass those generators and a bunch of other arguments that could be optional with happy defaults to the `DartDoc` constructor.

It would be ideal if there was a static method on the `DartDoc` class or if the constructor didn't require every piece of information be supplied when constructed so that programmatic usage of dartdoc could be as simple as possible.

**Comment by sethladd** [comment]
Could you write a wrapper that does exactly what you need?

Meanwhile, we're happy to check out an API proposal.

**Comment by evanweible-wf** [comment]
Yup that's no problem, that's what I'm going to do, I just opened this in hopes that this use case be kept in mind as this project moves forward.

**Comment by sethladd** [comment]
Great. However, without a specific API proposal, there's not much that's going to happen here. You have a specific use case in mind, which is great, so you have a specific API need.

I'm going to close because we don't have a specific idea in mind for this, but, please do reopen if you have a proposal.

Simple is better, so I look forward to learning what you need. We really appreciate your feedback!
