### ISSUE TITLE
provide a way to style output from dartdoc for re-use in other site templates

### ISSUE THREAD

**Issue by naomiblack** [dart-lang/dartdoc#942]
For Angular, we'd like to be able to export the HTML with a different template, to style it more like https://angular.io/docs/js/latest/api/core/APP_COMPONENT-const.html for re-use as part of that site.

Would be nice to support this feature (but not urgent)

**Comment by sethladd** [comment]
I think you can do this now, with a little work. dartdoc produces a model, which you can pass to a Generator. We only have one generator now: HtmlGenerator. But you could write your own generator.

if it's just style tweaks, you can use --header to insert styles into the header of every generated page.

I'm going to close this because I think you have what you need, but if you need something specific from the lower levels, please do let us know. Thanks!
