### ISSUE TITLE
/// characters turning up in generate docs

### ISSUE THREAD

**Issue by abarth** [dart-lang/dartdoc#974]
See http://domokit.github.io/docs/sky/animation/Performance/fling.html

```
Start running this animation according to the given physical parameters /// /// Flings the timeline with an optional force (defaults to a critically /// damped spring) and initial velocity. If velocity is positive, the /// animation will complete, otherwise it will dismiss.
```

The `///` shouldn't be in the generated docs.

https://github.com/flutter/engine/blob/master/sky/packages/sky/lib/src/animation/performance.dart#L156

**Comment by devoncarew** [comment]
Dup of https://github.com/dart-lang/dartdoc/issues/947, which has been fixed. We've published since then, but not rolled into an SDK which has been released. You should see better behavior if you run dartdoc via `pub global activate dartdoc; pub global run dartdoc` instead of running the sdk version.

**Comment by abarth** [comment]
Thanks!
